### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by lcottret** [biojs/registry-workmen#12]
In the github page, all the examples seem to be broken. 
Error message : e3: The workmen couldn't find a github repository:"no js found for the snippet"

**Comment by emepyc** [comment]
Could you provide links to specific examples?
AFAICS, this component has broken examples:
http://biojs.io/d/biojs-vis-scatter-plot

But all the others are working:
http://biojs.io/d/cytoscape
http://biojs.io/d/feature-viewer
etc

**Comment by emepyc** [comment]
And the problem with that specific example is that package.json refers to an example (many_samples_large) that doesn't exist in the examples folder

**Comment by lcottret** [comment]
Sorry, I made a mistake : the broken examples come from the github page 
of BioJs MSA (https://github.com/greenify/msa).
Example : http://workmen.biojs.net/demo/msa/fer1_annoted


Le 31/03/2016 14:14, Miguel Pignatelli a écrit :
>
> And the problem with that specific example is that package.json refers 
> to an example (many_samples_large) that doesn't exist in the examples 
> folder
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/biojs/registry-workmen/issues/12#issuecomment-203903560>
>

-- 
Ludovic COTTRET
INRA, 24 Chemin de Borde Rouge - Auzeville
CS 52627
31326 Castanet Tolosan cedex, France
Tel: +33 5.61.28.57.06  Fax : +33 5.61.28.50.61
Lab website:
http://www.toulouse.inra.fr/lipm
Personal website:
http://sites.google.com/site/lcottret/

**Comment by greenify** [comment]
Yeah I know about this - the registry is pretty old and only supports browserify builds. The msa uses webpack since two months and a started once on a fix, but then didn't deploy it. 

For the time being please look at the linked example page of the msa viewer at msa.biojs.net

Sorry for the inconveniences caused,

**Comment by lcottret** [comment]
So, it's maybe related to my other problem (https://github.com/greenify/msa/issues/112) : is it still possible to load msa in classical biojs project builds (as explained in http://edu.biojs.net/101/intro/) since biojs uses browsify and msa uses webpack ?

**Comment by greenify** [comment]
I found time to time to push my changes to biojs-util-snippets and now non-browserify packages are supported. It is just a small (hackish) additions that roughly goes like this
1) if `noBrowserify` -> disable inclusion of wrzd.in
2) `buildJS` can be used to point to an external script (for github you local urls are supported)

Sniper is updated too, there is still the hidden feature (`emu-snippets`) that simulates the registry. 

We should also change the download button in the registry ui accordingly for such packages.

The [MSA](http://biojs.io/d/msa) is now displayed again - the small style bug will be fixed soon.

> is it still possible to load msa in classical biojs project builds

Yes starting from 0.4.10
